---
sidebar: sidebar 
permalink: ai-policy.html 
---
= Política que prohíbe el uso del contenido generado por IA en la documentación técnica de NetApp
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
En NetApp, valoramos la experiencia de nuestros empleados, contratistas y partners a la hora de crear, publicar y mantener documentación técnica precisa, relevante y útil para nuestros clientes. Creemos que el uso del contenido generado por IA puede comprometer estos valores y socavar la integridad y precisión de nuestra documentación. Por tanto, una política de NetApp es prohibir la publicación de contenido generado por IA que no se haya verificado y validado por un ser humano. Esto se aplica a toda la documentación técnica publicada el docs.netapp.com. Tenga en cuenta que esta política es similar y amplía la política de NetApp que prohíbe el uso de modelos lingüísticos para escribir código en los productos que vende.

Esperamos que todos los colaboradores de NetAppDocs cumplan la siguiente política:

* No permitimos la publicación de documentación orientada a clientes (cómo usar productos de NetApp) generada a partir de la IA sin revisión ni validación humanas. Esto incluye materiales escritos, gráficos, multimedia u otros materiales que se publican en docs.netapp.com. Todos los contenidos publicados en docs.netapp.com deben ser verificados y validados por creadores de contenido humano.
* Parte del papel de creador de contenido para docs.netapp.com implica la adhesión a las guías de estilo y colaborador. Esto incluye estar informado sobre los últimos avances en contenido generado por la IA y de sus implicaciones en la documentación técnica de NetApp.
* Se espera que todos los empleados, contratistas y socios cumplan con la política. Las violaciones repetidas pueden resultar en privilegios de autor suspendidos.


Los colaboradores de NetAppDocs deben tener en cuenta lo siguiente:

* Todas las tecnologías de generación de contenido basadas en IA integradas en el software que ha instalado en su equipo de trabajo, incluidas aquellas como Microsoft 365 Co-Pilot, envían sus datos a la empresa que aloja la tecnología de asistencia. No solicite dicha tecnología con contenido confidencial de la empresa, incluidas, entre otras, las especificaciones para las características de producto no publicadas.
* No utilice tecnologías de IA públicas para generar o editar documentación técnica para **productos, versiones de productos o características no publicados previamente**.
* Los derechos de autor de la nueva documentación técnica deben permanecer en NetApp y no se deben compartir con AIS fuera de NetApp antes de las fechas de lanzamiento oficiales del producto ni de la publicación correspondiente de la documentación técnica relacionada.
* No envíe documentación confidencial, nuevos contenidos ni cualquier contenido escrito después de 2021, incluidas las URL, a AI (ChatGPT o cualquier otra herramienta). Cualquier información que se introduzca en ChatGPT se convierte en parte de su conjunto de datos de entrenamiento, que a su vez se convierte en propiedad de OpenAI y puede ser utilizada por ellos y sus usuarios. Si bien gran parte de estos datos son accesibles públicamente, no queremos entrenar el modelo en nuestra propia IP.

