---
settings:
  name: Contributor's Guide
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr
sidebar:
  entries:
  - title: Contribuir al contenido
    url: "/index.html"
  - title: Estilo para documentos de NetApp
    url: "/style.html"
  - title: Referencia AsciiDoc
    url: "/asciidoc_syntax.html"
  - title: Política sobre contenido generado por la IA
    url: "/ai-policy.html"
  - title: Avisos legales
    url: "/legal-notices.html"
