---
sidebar: sidebar 
permalink: style.html 
---
= Guía de estilos para documentos de NetApp
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Nuestro estilo es conversacional y empático, pero nos mantenemos profesionales y llegar al punto. Siga estas directrices al escribir contenido para documentos de NetApp.



== Escribir en conversacionalmente

Escriba como usted para hablar cuando le explique algo a un colega profesional. Escribir en un tono conversacional le ayuda a conectar con su audiencia.


TIP: Lea lo que ha escrito en voz alta. Como dijo Elmore Leonard, novelista y guionista estadounidense, “Si suena como escribir, lo reescribo”.

|===
| Demasiado formal | Demasiado informal | Nuestro estilo 


| Si tiene problemas con Cloud Tiering, puede ver el estado del estado en la consola del clúster para determinar por qué se ha producido el error. El estado refleja el estado del sistema ONTAP y del conector de servicio. | No es divertido cuando suceden fracasos. No te preocupes, sólo tienes que echar un vistazo al panel de instrumentos para ver lo que sucedió y lo que está afectado. | Cuando se produce un fallo, la organización en niveles en la nube muestra un estado de "error" en el Panel de clústeres. Consulte el estado para obtener información sobre el error. 


| Puede pagar por la organización en niveles del cloud de varias formas. Puede pagar por Cloud Tiering mediante una suscripción de pago por uso, puede pagar mediante una licencia de organización en niveles de ONTAP o puede pagar mediante una combinación de ambos. No puede obtener licencias desde Cloud Manager; debe dirigirse directamente al servicio Cloud Tiering para configurarlo. | Tenemos como tres formas de pagar por la organización en niveles del cloud. Una suscripción de pago por uso, pero también una licencia de organización en niveles de ONTAP o incluso una combinación de ambas. Pero no puede obtener licencias de Cloud Manager, así que solo tiene que ir directamente al servicio Cloud Tiering para configurarlo. | Pague por Cloud Tiering mediante una suscripción de pago por uso, una licencia de organización en niveles de ONTAP o una combinación de ambos. La licencia no está disponible desde Cloud Manager, pero puede dirigirse directamente al servicio Cloud Tiering para configurarlo. 


| Antes de poder aprovisionar almacenamiento, debe detectar el clúster de ONTAP en Cloud Manager. Una vez finalizada la detección, debe abrir el entorno de trabajo para aprovisionar el almacenamiento. | Todo lo que haga es descubrir en primer lugar su clúster de ONTAP desde Cloud Manager y, a continuación, abrir el entorno de trabajo para comenzar a aprovisionar almacenamiento. ¡Fácil! | Después de descubrir su clúster de ONTAP desde Cloud Manager, abra el entorno de trabajo para aprovisionar almacenamiento. 


| Analice los atributos de estado del sistema de almacenamiento de una de dos maneras, según lo que desee analizar: Seleccione el widget de atributo de estado de la consola o seleccione Ver todo para ver la lista completa de atributos de estado. | Tiene dos formas de analizar los atributos de bienestar de su sistema: Solo tiene que seleccionar el widget de atributo de bienestar en el panel de control. O bien, si prefiere ver toda la lista de atributos de bienestar en una sola vista, seleccione Ver todo. | Seleccione el widget de atributo de estado en el panel o seleccione Ver todo para ver la lista de todas las acciones y riesgos. 


| Cuando se inicie el asistente de configuración, siga las instrucciones del asistente para configurar el nodo y unirlo al clúster. Los siguientes pasos le guian por los pasos del asistente. | Aparece el asistente de configuración (casi como magia) para guiarle por el sencillo proceso de configurar el nodo y unirlo al clúster. | Siga las instrucciones del asistente de configuración para configurar el nodo y unirlo al clúster. 


| Puede elegir entre varios tipos de formatos de contenido para instalar y configurar el nuevo sistema. Cada tipo de formato proporciona instrucciones completas. Elija el tipo de formato que más se ajuste a la forma en que desee aprender. | ¿Cómo desea configurar e instalar el sistema? Proporcionamos instrucciones en varios tipos de formato de contenido, pero solo usted sabe cómo le gusta aprender. | Elija un tipo de formato de contenido que le guiará durante la instalación y configuración del sistema. 
|===


== Escribir con facilidad

Evite palabras grandes y confusas. Simplifique. Sino que explica algo a un colega profesional, que no muestra su vocabulario.

**En lugar de esta**: “Dissocie al usuario de su cuenta central de cloud de NetApp”.

**Haga esto**: “Elimine al usuario de su cuenta de Cloud Central de NetApp”.



== Escribir como mínimo

Las frases cortas y sencillas facilitan la lectura o exploración del contenido. Está bien usar una frase más larga cada vez y luego, pero seguir con una más corta. Así.

**En lugar de este**: “Para replicar datos entre un sistema Cloud Volumes ONTAP en sistemas AWS y ONTAP en otras redes, debe tener una conexión VPN entre Amazon VPC y la otra red, por ejemplo, un vnet de Azure o su red corporativa”.

**Haga esto**: “La replicación de datos entre redes requiere conexión a través de una VPN. Por ejemplo, entre Amazon VPC y su red corporativa o entre AWS y Azure”.

Consulte también <<minimalismo>>.



== Escribir activamente

Evitar la voz pasiva es una regla estándar para la escritura tecnológica, pero es especialmente importante usar la voz activa cuando se desea mantener la conversación.

**En lugar de este**: “Se deben proporcionar los permisos necesarios antes de implantar el primer clúster”.

**Haga esto**: “Proporcione los permisos necesarios antes de implementar el primer clúster”.

Consulte también <<voz activa (frente a “voz pasiva”)>>.



== Usar un idioma inclusivo

NetApp cree que la documentación de sus productos no debe contener un lenguaje discriminatorio y exclusivo. Las palabras que utilizamos pueden marcar la diferencia entre forjar una relación positiva con nuestros clientes o alejarlos. Especialmente con palabras escritas, el impacto es más importante que la intención.

Mientras crea contenido para los productos de NetApp, evite cualquier lenguaje que se pueda interpretar como degradante, racista, sexista u otro tipo de opresión. En su lugar, utilice un idioma accesible y acogedor para todo aquel que necesite utilizar la documentación. Por ejemplo, en lugar de "maestro/esclavo", utilice "primario/secundario".

Sabemos que tenemos trabajo que hacer para eliminar todo el lenguaje no incluido de nuestra documentación y nuestros productos. Estamos trabajando activamente en nuestros estándares y prácticas recomendadas y esperamos actualizar esta sección con orientación adicional en el futuro.



== Llegar al punto

Comience con lo que es importante para el usuario. Averigüe qué es lo que el usuario está intentando hacer y céntrese en ayudarles a alcanzar ese objetivo.

**En lugar de este**: “Cloud Sync puede sincronizar datos de un servidor NFS con otro servidor NFS mediante el cifrado de datos en vuelo. Cifrar los datos puede ayudar si tiene estrictas políticas de seguridad para transferir datos a través de redes.”

**Haga esto**: “Si su empresa tiene políticas de seguridad estrictas, utilice el cifrado de datos en vuelo para sincronizar datos entre servidores NFS en diferentes redes”.



== Utiliza muchas imágenes

La mayoría de las personas son estudiantes visuales. Utilice vídeos, diagramas y capturas de pantalla para mejorar el aprendizaje. Los elementos visuales también ayudan a dividir bloques de texto.

.Ejemplos
* https://docs.netapp.com/us-en/occm/concept_accounts_aws.html["Ejemplo #1"^]
* https://docs.netapp.com/us-en/occm/task_getting_started_azure.html["Ejemplo #2"^]


Consulte también <<gráficos>>.



== Crear contenido que pueda ser canificable

Utilice encabezados, listas y tablas para ayudar a los usuarios a buscar lo que desean.

.Ejemplos
* https://docs.netapp.com/us-en/cloud_volumes/aws/task_activating_support_entitlement.html["Ejemplo #1"^]
* https://docs.netapp.com/us-en/cloud_volumes/aws/reference_selecting_service_level_and_quota.html["Ejemplo #2"^]




== Centrarse en un objetivo del usuario o en un aspecto específico de ese objetivo

Si está describiendo cómo completar una serie de tareas, póngela todo en una página de una serie de secciones, incluida información conceptual y basada en referencias. No divida su página en varias mini páginas, lo que requiere demasiado clic. Al mismo tiempo, no cree páginas largas e intimidantes. Use su mejor juicio para decidir cuándo una página es demasiado larga.

.Ejemplos
* https://docs.netapp.com/us-en/cloud_volumes/aws/task_activating_support_entitlement.html["Ejemplo #1"^]
* https://docs.netapp.com/us-en/occm/concept_ha.html["Ejemplo #2"^]




== Organice el contenido según el objetivo del usuario

Ayude a los usuarios a encontrar la información que necesitan cuando la necesitan. Para ponerlos y sacarlos de los documentos lo antes posible, organice el contenido de la siguiente forma:

Primera entrada en la navegación izquierda (nivel alto):: Organice el contenido alrededor de los objetivos que el usuario intenta alcanzar. Por ejemplo, primeros pasos o protección de datos.
Las segundas entradas de la navegación (nivel medio):: Organice el contenido alrededor de las amplias tareas que componen las metas. Por ejemplo, configurar la recuperación ante desastres o configurar la protección de datos.
Páginas individuales (nivel detallado):: Organice el contenido alrededor de las tareas individuales que componen las tareas amplias, con cada una centrada en un solo aprendizaje o haciendo un aspecto de esa amplia tarea. Por ejemplo, las tareas necesarias para configurar la recuperación ante desastres.




== Escribir para un público global

Escribimos para nuestros clientes y socios de todo el mundo, y gran parte de nuestro contenido se traduce mediante herramientas de traducción automática neuronal o traducción humana. Siga estas directrices para una redacción más clara y una traducción más sencilla:

* Escribir frases cortas y sencillas.
* Utilice gramática y puntuación estándar.
* Utilice una palabra para un significado y un significado para una palabra.
* Utilice contracciones comunes.
* Utilice gráficos para aclarar o reemplazar texto.
* Evite incrustar texto en gráficos.
* Evite tener tres o más nombres en una cadena.
* Evitar antecedentes poco claros.
* Evitar la jerga, los coloquialismos y las metáforas.
* Evite ejemplos no técnicos.
* Evite utilizar retornos duros y espaciado.
* No use el humor ni la ironía.
* No utilice contenido discriminatorio.
* No utilice un lenguaje de género a menos que usted esté escribiendo para una persona específica.




== Directrices de la a a la Z.



=== voz activa (frente a “voz pasiva”)

En voz activa, el tema de la frase es el doer de la acción:

* Si apaga el sistema de forma incorrecta, la interfaz muestra un mensaje de advertencia.
* NetApp ha recibido el contrato.


La voz activa mantiene la grabación nítida y clara. Utilice los usuarios activos de voz y dirección directamente como “usted” a menos que tenga una razón específica para usar la voz pasiva.

En voz pasiva, el hacedor de la acción no está claro:

* Se muestra un mensaje de advertencia si el sistema se apaga incorrectamente.
* NetApp ha sido galardonado con el contrato.


Utilizar voz pasiva cuando:

* Usted no sabe quién o qué realizó la acción.
* Usted quiere evitar culpar a los usuarios por los resultados de una acción.
* No se puede escribir a su alrededor, como por ejemplo para obtener información previa.


Para convenciones adicionales de verbo, consulte:

* https://docs.microsoft.com/en-us/style-guide/welcome/["Guía de estilo de escritura de Microsoft"^]
* https://www.chicagomanualofstyle.org/home.html["Manual de estilo de Chicago"^]
* https://www.merriam-webster.com/["Merriam-Webster Diccionario en línea"^]




=== admoniciones

Utilice las siguientes etiquetas para identificar el contenido por separado del flujo de contenido principal:

* NOTA
+
Utilice LA NOTA para obtener información importante que debe ser distinta del resto del texto. Evite utilizar UNA NOTA para obtener información “agradable de conocer” que no es necesaria para que los usuarios aprendan sobre la tarea o completen la tarea.

* CONSEJO
+
Use LA SUGERENCIA con moderación, si es que es que se trata de hacerlo, porque nuestra política es documentar siempre la información de las mejores prácticas de forma predeterminada. Si es necesario, use CONSEJO para contener información sobre las mejores prácticas que ayude a los usuarios a utilizar un producto o a completar un paso o una tarea de forma fácil y eficaz.

* PRECAUCIÓN
+
Tenga cuidado al advertir a los usuarios sobre condiciones o procedimientos que pueden causar lesiones personales que no sean letales o extremadamente peligrosas.





=== después (frente a “una vez”)

* Utilice “después” para indicar una cronología: “Encienda el ordenador después de enchufarlo”.
* Utilice “una vez” sólo para indicar “una vez”.




=== también

* Utilice "también" para indicar "adicionalmente".
* No utilice "también" para decir "alternativamente".




=== y/o.

Elija el término más preciso si hay uno. Si ninguno de los dos términos es más preciso que el otro, utilice “y/o”.



=== como

No utilice “como” para decir “porque”.



=== mediante el uso (frente a “uso” o “con”)

* Utilice “utilizando” cuando la entidad que está haciendo el uso es el tema: “Puede agregar nuevos componentes al repositorio mediante el menú componentes”.
* Puede empezar una frase con "usar" o "con", que a veces son aceptables con los nombres de productos: "Con SnapDrive, puede administrar discos virtuales y copias Snapshot en un entorno Windows".




=== can (frente a “poder”, “puede”, “debe” o “debe”)

* Utilice “CAN” para indicar capacidad: “Puede confirmar los cambios en cualquier momento durante este procedimiento”.
* Utilice “podría” para indicar la posibilidad: “La descarga de varios programas podría afectar al tiempo de procesamiento”.
* No utilice “el mayo”, lo cual es ambiguo porque podría significar capacidad o permiso.
* Utilice “debería” para indicar una acción recomendada pero opcional. Consideremos, en cambio, usar una frase alternativa, como “recomendamos”.
* Evite usar “debe” porque es pasivo. Considere la posibilidad de reestablecer el pensamiento como una instrucción utilizando la voz imperativa. Si utiliza “debe”, utilícelo para indicar una acción o condición necesaria.




=== capitalización

Utilice mayúsculas de estilo de frase (minúsculas) para casi todo. Solo capitalice:

* La primera palabra de frases y encabezados, incluidos los títulos de las tablas
* La primera palabra de los elementos de la lista, incluidos los fragmentos de frase
* Unas adecuadas
* Títulos de documentos y subtítulos (capitalice todas las palabras y preposiciones principales de cinco o más letras)
* Elementos de la interfaz de usuario, pero solo si están capitalizados en la interfaz. De lo contrario, utilice minúsculas.




=== Avisos de PRECAUCIÓN

Tenga cuidado al advertir a los usuarios sobre condiciones o procedimientos que pueden causar lesiones personales que no sean letales o extremadamente peligrosas.

Consulte <<admoniciones>> para otras etiquetas que identifican el contenido por separado del flujo de contenido principal.



=== coherencia

“Escribir como usted habla cuando usted está explicando algo a un colega profesional” significa algo diferente a todos. Nuestro estilo de conversación profesional nos ayuda a conectarnos a los usuarios y aumenta la frecuencia de incoherencias menores entre varios autores que contribuyen:

* Céntrese en hacer el contenido claro y fácil de usar. Si todo el contenido es claro y fácil de usar, las inconsistencias menores no importan.
* Sea coherente dentro de la página que está escribiendo.
* Siga siempre las directrices de <<Escribir para un público global>>.




=== contracciones

Las contracciones refuerzan un tono conversacional, y muchas contracciones son fáciles de entender y traducir.

* Utilice contracciones como estas, que son fáciles de entender y traducir:
+
|===


| no lo es | ya lo está 


| no es | por ahora 


| no lo era | sí 


| no lo fueron | vamos 


| no lo hizo | lo haremos (si se requiere tiempo futuro) 


| no lo hace | no lo hará (si se requiere tiempo futuro) 


| no lo hagas | usted (si se requiere tiempo futuro) 
|===
* No utilice contracciones como estas, que son difíciles de entender y traducir:
+
|===


| lo habría sido | debería haber sido así 


| no habría sido así | no debería haber sido así 


| podría haber sido así | no podría haber sido así 
|===




=== asegurarse (en comparación con "confirmar" o "verificar")

* Utilice "asegurar" para indicar "asegurarse". Incluya “eso”, según proceda: "Asegúrese de que haya suficiente espacio en blanco alrededor de las ilustraciones."
* Nunca use “asegurar” para implicar una promesa o garantía: “Usar Cloud Manager para garantizar que puede aprovisionar volúmenes NFS y CIFS en clústeres de ONTAP”.
* Utilice “Confirmar” o “verificar” cuando signifique que el usuario debe comprobar dos veces algo que ya existe o que ya ha ocurrido: “Compruebe que NFS está configurado en el clúster”.




=== gráficos

Evalúe continuamente el contenido para oportunidades de incluir ilustraciones útiles, diagramas, diagramas de flujo, capturas de pantalla u otras referencias visuales. Los gráficos a menudo transmiten conceptos complejos y pasos más claramente que el texto.

* Incluya una descripción de la intención de la ilustración de comunicar: “En la siguiente ilustración se muestran los LED de la fuente de alimentación de CA en el panel posterior.
* Consulte la ubicación de la ilustración como "siguiente" o "anterior", no "arriba" o "abajo".




=== gramática

Salvo que se indique lo contrario, siga las convenciones de gramática, puntuación y ortografía detalladas en:

* https://docs.microsoft.com/en-us/style-guide/welcome/["Guía de estilo de escritura de Microsoft"^]
* https://www.chicagomanualofstyle.org/home.html["Manual de estilo de Chicago"^]
* https://www.merriam-webster.com/["Merriam-Webster Diccionario en línea"^]




=== si no es así

No utilice “si no” por sí solo para referirse a la frase anterior:

**En lugar de este**: “El ordenador debería estar apagado. Si no es así, apáguela.”

**Haga esto**: "Verifique que el ordenador esté apagado".



=== si (frente a “si” o “cuándo”)

* Utilice “if” para indicar una condición, como en "si esto, entonces eso" construcciones.
* Use "si" cuando haya una condición declarada o implícita "o no". Para facilitar la traducción, a menudo es mejor reemplazar "ya sea o no" por "solo".
* Use “cuándo” para indicar un paso de tiempo.




=== voz imperativa

* Utilice la voz imperativa para los pasos, directivas, solicitudes y encabezados de las listas de acciones de los usuarios:
+
** “En la página entornos de trabajo, haga clic en detectar y seleccione clúster de ONTAP”.
** “Gire el mango de la leva para que quede al ras con la fuente de alimentación.”


* Considere la posibilidad de utilizar la voz necesaria para sustituir la voz pasiva:
+
**En lugar de este**: “Se deben proporcionar los permisos necesarios antes de implantar el primer clúster”.

+
**Haga esto**: “Proporcione los permisos necesarios antes de implementar el primer clúster”.

* Evite utilizar la voz imperativa para incrustar pasos en la información conceptual y de referencia.




=== Direcciones IP e IPv6

Para las direcciones IP (incluida IPv6) en ejemplos, es seguro incluir cualquier dirección que empiece por “10.x”.



=== futuras funcionalidades o versiones

No haga referencia a la programación o el contenido de las próximas versiones o funciones de productos, excepto para decir que una función o función “actualmente no es compatible”.



=== Artículos de KB: Referencia a.

Consulte los artículos de la base de conocimientos de NetApp (NetApp Knowledgebase) cuando corresponda. Para páginas de recursos y contenido de GitHub, coloque el vínculo en texto en ejecución.



=== listas

Las listas de información suelen ser más fáciles de escanear y absorber que los bloques de texto. Considere formas de simplificar la información compleja presentándola en forma de lista. A continuación se indican algunas directrices generales, pero use su criterio:

* Asegúrese de que el motivo de la lista está claro. Introduzca la lista con una frase completa, un fragmento de frase con dos puntos o un encabezado.
* Las listas deben tener entre dos y siete entradas. En general, cuanto más corta sea la información de cada entrada, más entradas podrá agregar mientras mantiene la lista en un estado de exploración.
* Las entradas de lista deben ser lo más explorables posible. Evite bloques de texto que se puedan escanear para mantener las entradas de la lista.
* Las entradas de la lista deben comenzar con una letra mayúscula, y las entradas de la lista deben ser gramaticalmente paralelas. Por ejemplo, comience cada entrada con un sustantivo o un verbo:
+
** Si todas las entradas de la lista son frases completas, terminarlas con períodos.
** Si todas las entradas de la lista son fragmentos de frase, no las finalice con puntos.


* Las entradas de lista deben ordenarse de forma lógica, como alfabéticamente o cronológicamente.




=== localización

Consulte <<Escribir para un público global>>.



=== minimalismo

* ¿Los usuarios necesitan este contenido en este lugar, en este momento?
* ¿Puedo presentar el contenido en menos palabras sin sonar demasiado formal o demasiado informal?
* ¿Puedo acortar o simplificar una frase larga o dividirla en dos o más frases?
* ¿Puedo utilizar una lista para hacer que el contenido sea más explorable?
* ¿Puedo utilizar un gráfico para aumentar o reemplazar un bloque de texto?




=== Información de NOTAS

Utilice LA NOTA para obtener información importante que debe ser distinta del resto del texto. Evite utilizar UNA NOTA para obtener información “agradable de conocer” que no es necesaria para que los usuarios aprendan sobre la tarea o completen la tarea.

Consulte <<admoniciones>> para otras etiquetas que identifican el contenido por separado del flujo de contenido principal.



=== números

* Utilice números arábigos para 10 y todos los números mayores de 10, con las siguientes excepciones:
+
** Si comienza una frase con un número, utilice una palabra, no un número árabe.
** Utilice palabras (no números) para números aproximados.


* Utilice palabras para números menores de 10.
* Si una frase contiene una mezcla de números menores de 10 y mayores de 10, utilice números árabes para todos los números.
* Para conocer las convenciones de números adicionales, consulte:
+
** https://docs.microsoft.com/en-us/style-guide/welcome/["Guía de estilo de escritura de Microsoft"^]
** https://www.chicagomanualofstyle.org/home.html["Manual de estilo de Chicago"^]






=== plagio

Documentamos los productos de NetApp y la interacción de los productos de NetApp con productos de terceros. No documentamos productos de terceros. Nunca deberíamos copiar y pegar contenido de terceros en nuestros documentos y no deberíamos hacerlo nunca.



=== requisitos previos

Los requisitos previos identifican las condiciones que deben existir o las acciones que los usuarios deben haber completado antes de iniciar la tarea actual.

* Identifique la naturaleza del contenido con un encabezado, como “requisitos previos”, “antes de empezar” o “antes de empezar”.
* Utilice la voz pasiva para la redacción de los requisitos previos si tiene sentido hacerlo:
+
** “Es necesario configurar NFS o CIFS en el clúster”.
** “Debe tener la dirección IP de administración del clúster y la contraseña de la cuenta de usuario administrador para añadir el clúster a Cloud Manager”.


* Aclare el requisito previo según sea necesario: “Debe configurarse NFS o CIFS en el clúster. Puede configurar NFS y CIFS mediante System Manager o la CLI.”
* Considere otras formas de presentar la información, por ejemplo, si sería apropiado volver a escribir el contenido como el primer paso de la tarea actual:
+
** Requisito previo: “Debe tener los permisos necesarios antes de implementar el primer clúster”.
** Paso: “Proporcione los permisos necesarios para implementar el primer clúster”.






=== anterior (frente a "antes", "anterior" o "anterior")

* Si es posible, sustituya "anterior" por "antes".
* Si no se puede usar “antes”, use “previos” como adjetivo para referirse a algo que ocurrió antes en el tiempo o con un orden de importancia mayor.
* Use “Previous” para indicar algo que ocurrió en un momento no especificado antes.
* Use “precedente” para indicar algo que ocurrió inmediatamente antes.




=== signos de puntuación

Simplifique. En general, mientras más puntuación se incluya en una frase, más células cerebrales se necesita entender.

* Utilice una coma en serie (coma Oxford) antes de la conjunción (“y” o “o”) en una lista narrativa de tres o más artículos.
* Limite el uso de punto y coma.
* Salvo que se indique lo contrario, siga las convenciones de gramática, puntuación y ortografía detalladas en:
+
** https://docs.microsoft.com/en-us/style-guide/welcome/["Guía de estilo de escritura de Microsoft"^]
** https://www.chicagomanualofstyle.org/home.html["Manual de estilo de Chicago"^]
** https://www.merriam-webster.com/["Merriam-Webster Diccionario en línea"^]






=== desde entonces

Use “since” para indicar un paso de tiempo. No utilice "desde" para decir "porque".



=== ortografía

Salvo que se indique lo contrario, siga las convenciones de gramática, puntuación y ortografía detalladas en:

* https://docs.microsoft.com/en-us/style-guide/welcome/["Guía de estilo de escritura de Microsoft"^]
* https://www.chicagomanualofstyle.org/home.html["Manual de estilo de Chicago"^]
* https://www.merriam-webster.com/["Merriam-Webster Diccionario en línea"^]




=== eso (en vez de “qué” o “quién”)

* Utilice “que” (sin una coma de salida) para introducir cláusulas que sean necesarias para que la frase tenga sentido.
* Use “que” incluso si la frase es clara en inglés sin ella: "Verifique que el ordenador esté apagado".
* Utilice “qué” (con una coma final) para introducir cláusulas que añadan información complementaria pero que no sean necesarias para que la frase tenga sentido.
* Use “OMS” para introducir cláusulas que se refieran a las personas.




=== INFORMACIÓN sobre CONSEJOS

Use LA SUGERENCIA con moderación, si es que es que se trata de hacerlo, porque nuestra política es documentar siempre la información de las mejores prácticas de forma predeterminada. Si es necesario, use CONSEJO para contener información sobre las mejores prácticas que ayude a los usuarios a utilizar un producto o a completar un paso o una tarea de forma fácil y eficaz.

Consulte <<admoniciones>> para otras etiquetas que identifican el contenido por separado del flujo de contenido principal.



=== marcas comerciales

No incluimos símbolos de marcas en la mayor parte de nuestro contenido técnico porque las declaraciones legales de nuestras plantillas son suficientes. Sin embargo, sí seguimos todas las reglas de uso cuando las utilizamos https://www.netapp.com/us/legal/netapptmlist.aspx["Condiciones de Marca comercial de NetApp"^]:

* Use términos de marcas (con o sin el símbolo) sólo como adjetivos, nunca como sustantivos, verbos o verzales.
* No abrevie, hiphenate, o en cursiva los términos de la Marca registrada.
* No pluralice los términos de marcas comerciales. Si se requiere una forma plural, use el nombre de la Marca registrada como adjetivo que modifica un sustantivo plural.
* No utilice una forma posesiva de un término de Marca registrada. Puede utilizar la forma posesiva de nombres de empresa, como NetApp, cuando los nombres se utilizan en sentido general, en lugar de como términos de Marca comercial.




=== interfaz de usuario

Confíe en la interfaz tanto como sea posible para guiar al usuario.



==== Directrices generales

Nuestro estilo de documentación de las interfaces de usuario es sencillo y mínimo:

* Suponga que el usuario está utilizando la interfaz mientras lee el contenido.
* Confíe en la interfaz para guiar al usuario:
+
** No guíe al usuario paso a paso a través de un asistente o una pantalla. Sólo llame a las cosas importantes que no son aparentes desde la interfaz.
** No incluya “haga clic en Aceptar”, “haga clic en Guardar” o “el volumen se crea” o cualquier otra cosa que resulte obvia para alguien que realice la tarea.
** Presuponga éxito. A menos que espere que una operación falle la mayoría de las veces, no documente la ruta de fallos. Supongamos que la interfaz proporciona una guía adecuada.


* No utilice "clic" en absoluto. Utilice siempre “SELECT” porque esa palabra cubre el ratón, la pulsación, el teclado y cualquier otra forma de elegir.
* Centre el contenido en un flujo de trabajo que aborde un caso de uso del cliente y haga que el usuario tenga el lugar adecuado en la interfaz para iniciar el flujo de trabajo.
* Documente siempre la mejor manera de lograr el objetivo del usuario.
* Si el flujo de trabajo requiere una decisión significativa, asegúrese de documentar una regla de decisión.
* Utilice el número mínimo de pasos necesario para la mayoría de usuarios la mayor parte del tiempo.




==== Nomenclatura de los elementos de la IU

Evite documentar el nivel de granularidad que requiera la nomenclatura de elementos de la interfaz de usuario. Confíe en la interfaz para guiar al usuario a través de los detalles de la interacción. Si debe obtener ese valor específico, asigne un nombre a la etiqueta en el elemento. Por ejemplo, “Seleccione el volumen deseado” o “Seleccione ‘utilizar volumen existente’”. No es necesario nombrar menús, botones de opción o casillas de verificación, sólo tiene que utilizar la etiqueta.

Para los iconos que deben seleccionar los usuarios, utilice una imagen del icono. No intente darle un nombre. Esta regla se aplica a iconos como la flecha, lápiz, engranaje, kabob, hamburguesa, y así sucesivamente.



==== Representación de las etiquetas mostradas

Siga la ortografía y el uso de mayúsculas que utiliza la interfaz de usuario al identificar etiquetas. Si a una etiqueta le siguen tres puntos, no incluya los tres puntos al asignar nombre al objeto. ANIME a los desarrolladores a utilizar mayúsculas en el estilo de título para las etiquetas de interfaz de usuario, para que la escritura sea más sencilla.



==== Uso de capturas de pantalla

Una captura de pantalla ocasional (“screenshot”) ayuda a los usuarios a estar seguros de que están en el lugar correcto de una interfaz al iniciar o cambiar interfaces durante un flujo de trabajo. No utilice capturas de pantalla para mostrar qué datos desea introducir o qué valor seleccionar.



=== mientras (frente a “aunque”)

* Use “Time” para indicar algo que ocurre a tiempo.
* Use “aunque” para representar una actividad que se produce casi al mismo tiempo o poco después de otra actividad.




=== flujo de trabajo

Los usuarios leen nuestro contenido para lograr un objetivo específico. Los usuarios quieren encontrar el contenido que necesitan, lograr sus metas y ir a casa a sus familias. Nuestro trabajo no consiste en documentar productos o funciones, nuestro trabajo es documentar los objetivos del usuario. Los flujos de trabajo son la forma más directa de ayudar a los usuarios a lograr sus objetivos.

Un flujo de trabajo es una serie de pasos o subtareas que describen cómo alcanzar un objetivo de usuario. El alcance de un flujo de trabajo es un objetivo completo.

Por ejemplo, los pasos para crear un volumen no serían un flujo de trabajo, ya que crear un volumen en sí mismo no es un objetivo completo. Los pasos para poner el almacenamiento a disposición de un servidor ESX pueden ser un flujo de trabajo. Los pasos incluirán no solo la creación de un volumen, sino la exportación del volumen, la configuración de los permisos necesarios, la creación de una interfaz de red, etc. Los flujos de trabajo se derivan de los casos prácticos de los clientes. Un flujo de trabajo muestra sólo la mejor manera de alcanzar el objetivo.
