---
sidebar: sidebar 
permalink: style.html 
---
= Guía de estilos para documentos de NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nuestro estilo es conversacional y empático, pero nos mantenemos profesionales y llegar al punto. Siga estas directrices al escribir contenido para documentos de NetApp.



== Escribir en conversacionalmente

Escriba como si hablara cuando le esté explicando algo a un colega profesional. Escribir en un tono conversacional le ayuda a conectar con su audiencia.

|===
| Demasiado formal | Demasiado informal | Nuestro estilo 


| Si tienes problemas con la organización en niveles de BlueXP, puedes ver el estado en la consola de clúster para determinar por qué se ha producido el error. El estado refleja el estado del sistema ONTAP y del conector de servicio. | No es divertido cuando ocurren los fallos. Sin embargo, no se preocupe, simplemente eche un vistazo a la consola de clúster para ver qué ha sucedido y qué está afectado. | Cuando se produce un error, la organización en niveles de BlueXP muestra el estado «Failed» en la consola de clúster. Consulte el estado para obtener información sobre el error. 


| Para poder aprovisionar el almacenamiento, tienes que detectar tu clúster de ONTAP en BlueXP. Una vez finalizada la detección, debe abrir el entorno de trabajo para aprovisionar el almacenamiento. | Todo lo que haces es detectar primero tu clúster ONTAP desde BlueXP y, a continuación, abrir el entorno de trabajo para empezar a aprovisionar el almacenamiento. ¡Fácil! | Después de descubrir tu clúster ONTAP de BlueXP, abre el entorno de trabajo para aprovisionar almacenamiento. 


| Cuando se inicie el asistente de configuración, siga las instrucciones del asistente para configurar el nodo y unirlo al clúster. Los siguientes pasos le guian por los pasos del asistente. | Aparece el asistente de configuración (casi como magia) para guiarle por el sencillo proceso de configurar el nodo y unirlo al clúster. | Siga las instrucciones del asistente de configuración para configurar el nodo y unirlo al clúster. 


| Puede elegir entre varios tipos de formatos de contenido para instalar y configurar el nuevo sistema. Cada tipo de formato proporciona instrucciones completas. Elija el tipo de formato que más se ajuste a la forma en que desee aprender. | ¿Cómo desea configurar e instalar el sistema? Proporcionamos instrucciones en varios tipos de formato de contenido, pero solo usted sabe cómo le gusta aprender. | Elija un tipo de formato de contenido que le guiará durante la instalación y configuración del sistema. 
|===


=== Utilice contracciones

Las contracciones refuerzan a <<Escribir en conversacionalmente,tono de conversación>>, y muchas contracciones son fáciles de entender y traducir.

.Amplíe para obtener más información
[%collapsible]
====
* Utilice contracciones como estas, que son fáciles de entender y traducir:
+
|===


| no lo es | lo es 


| no es | por ahora 


| no lo era | sí 


| no lo fueron | vamos 


| no lo hizo | lo haremos (si se requiere tiempo futuro) 


| no lo hace | no lo hará (si se requiere tiempo futuro) 


| no lo hagas | usted (si se requiere tiempo futuro) 
|===
* No utilice contracciones como estas, que son difíciles de entender y traducir:
+
|===


| lo habría hecho | debería haber 


| no lo habría hecho | no debería haber 


| podría haberlo hecho | no podía haber 
|===


====


== Escribir con facilidad

Evite palabras grandes y confusas. Simplifique. Estás explicando algo a un colega profesional, sin mostrar tu vocabulario.

**En lugar de esto**: “Disociar al usuario de su cuenta central en la nube de NetApp”.

**Haz esto**: “Elimina al usuario de tu cuenta central en la nube de NetApp”.



== Escribir como mínimo

Las frases cortas y sencillas facilitan la lectura o exploración del contenido. Está bien usar una oración más larga de vez en cuando, pero seguirla con una más corta. Así.

**En lugar de esto**: “Para replicar datos entre un sistema Cloud Volumes ONTAP en AWS y los sistemas ONTAP en otras redes, debe tener una conexión VPN entre la VPC de Amazon y la otra red, por ejemplo, una vnet de Azure o su red corporativa”.

**Haga esto**: “La replicación de datos entre redes requiere conexión a través de una VPN. Por ejemplo, entre su Amazon VPC y su red corporativa o entre AWS y Azure».

Pregúntate lo siguiente:

* ¿Los usuarios necesitan este contenido en este lugar, en este momento?
* ¿La interfaz de usuario ya guía al usuario lo suficientemente bien? Si no es así, ¿qué guía adicional se puede agregar sucintamente?
* ¿Puedo presentar el contenido en menos palabras sin sonar demasiado formal o demasiado informal?
* ¿Puedo acortar o simplificar una frase larga o dividirla en dos o más frases?
* ¿Puedo utilizar una lista para hacer que el contenido sea más explorable?
* ¿Puedo utilizar un gráfico para aumentar o reemplazar un bloque de texto?




== Escribir activamente

Evitar la voz pasiva es una regla estándar para la escritura de tecnología, pero es especialmente importante usar la voz activa cuando se quiere sonar conversacional.



=== Voz activa

Utilice la voz activa para que el sujeto de la oración realice la acción del verbo. Esto normalmente significa que el verbo sigue al sujeto de la oración. La voz activa mantiene la grabación nítida y clara. Utilice la voz activa y dirija a los usuarios directamente como “usted” a menos que tenga una razón específica para usar la voz pasiva.

Aquí hay algunos ejemplos de buena escritura de voz activa. Escribe así:

* Proporcione los permisos necesarios antes de implementar el primer clúster.
* Si apaga el sistema incorrectamente, la interfaz muestra un mensaje de advertencia.
* NetApp ha recibido el contrato.




=== Voz pasiva

En voz pasiva, el hacedor de la acción no está claro:

* Se muestra un mensaje de advertencia si el sistema se apaga incorrectamente.
* NetApp ha sido galardonado con el contrato.


Utilizar voz pasiva cuando:

* No sabes quién o qué realizó la acción.
* Usted quiere evitar culpar a los usuarios por los resultados de una acción.
* No se puede escribir alrededor de él, como por ejemplo para alguna información de requisitos previos.




=== Estado de ánimo imperativo

Utilice el estado de ánimo imperativo para los pasos, directivas, solicitudes y encabezados de las listas de acciones del usuario:

* En la página Working Environments, haga clic en Discover and select ONTAP Cluster.
* Gire el asa de la leva para que quede a ras de la fuente de alimentación.


Considere la posibilidad de utilizar la voz necesaria para sustituir la voz pasiva:

**En lugar de esto**: “Los permisos requeridos deben ser proporcionados antes de implementar su primer clúster”.

**Haz esto**: “Proporciona los permisos necesarios antes de implementar tu primer clúster”.

Evite utilizar la voz imperativa para incrustar pasos en la información conceptual y de referencia.

Para convenciones adicionales de verbo, consulte:

* https://docs.microsoft.com/en-us/style-guide/welcome/["Guía de estilo de escritura de Microsoft"^]
* https://www.merriam-webster.com/["Merriam-Webster Diccionario en línea"^]




== Escribir contenido coherente

“Escribir como si hablara cuando le estás explicando algo a un colega profesional” significa algo diferente para todos. Nuestro estilo profesional pero conversacional nos ayuda a conectarnos con los usuarios y aumenta la frecuencia de incoherencias menores entre los múltiples autores contribuyentes:

* Céntrese en hacer el contenido claro y fácil de usar. Si todo el contenido es claro y fácil de usar, las inconsistencias menores no importan.
* Sea consistente dentro de la página que está escribiendo.
* Siga siempre las directrices de <<Escribir para un público global>>.




== Usar un idioma inclusivo

NetApp cree que la documentación de sus productos no debe contener un lenguaje discriminatorio y exclusivo. Las palabras que utilizamos pueden marcar la diferencia entre forjar una relación positiva con nuestros clientes o alejarlos. Especialmente con palabras escritas, el impacto es más importante que la intención.

Mientras crea contenido para los productos de NetApp, evite cualquier lenguaje que se pueda interpretar como degradante, racista, sexista u otro tipo de opresión. En su lugar, utilice un idioma accesible y acogedor para todo aquel que necesite utilizar la documentación. Por ejemplo, en lugar de "maestro/esclavo", utilice "primario/secundario".

Use el lenguaje de las personas primero donde nos referimos primero a la persona, seguido por la discapacidad.

No uses él, él, el suyo, ella, ella, o la suya en referencias genéricas. En su lugar:

* Reescribe la frase para usar la segunda persona (tú).
* Reescribe la oración para tener un sustantivo plural y pronombre.
* Utilice “el” o “a” en lugar de un pronombre (por ejemplo, “el documento”).
* Consulte el rol de una persona (por ejemplo, lector, empleado, cliente o cliente).
* Use el término “persona” o “individuo”.


*Ejemplos de palabras y frases que se consideran inclusivas o exclusivas*

[cols="50,50"]
|===
| Ejemplos inclusivos | Ejemplos exclusivos 


| Primario/secundario | Maestro/esclavo 


| Lista permitida | Lista blanca 


| Lista bloqueada | Lista negra 


| Pare | Matar 


| Deje de responder | Colgar 


| Finalizar o Cancelar | Anular 


| Hora de la persona | Hora del hombre 


| Los desarrolladores necesitan acceder a los servidores en sus entornos de desarrollo, pero no necesitan acceder a los servidores de Azure. | Un desarrollador necesita acceso a los servidores en su entorno de desarrollo, pero no necesita acceso a los servidores en Azure. 


| Persona ciega | Para huéspedes con limitaciones visuales 


| Persona con baja visión | Problemas de visión 
|===


== Llegar al punto

Cada página debe comenzar con lo que es más importante para el usuario. Tenemos que averiguar lo que el usuario está tratando de hacer y enfocarnos en ayudarles a lograr ese objetivo. También debemos agregar palabras clave al principio de la oración para mejorar la capacidad de escaneo.

Siga estas directrices generales de frases:

* Sea preciso.
* Evite las palabras de relleno.
* Sea corto.
* Utilice texto con formato o listas con viñetas para resaltar los puntos clave.


*Ejemplos de llegar al punto*

|===
| Buenos ejemplos | Ejemplos erróneos 


| Si su empresa tiene políticas de seguridad estrictas, utilice el cifrado de datos en tránsito para sincronizar los datos entre servidores NFS en diferentes redes. | Cloud Sync puede sincronizar datos de un servidor NFS con otro servidor NFS mediante el cifrado de datos en tránsito. Cifrar los datos puede ayudar si tiene políticas de seguridad estrictas para transferir datos a través de redes. 


| Ahorre tiempo creando una plantilla de documento que incluya los estilos, formatos y diseños de página que utiliza con más frecuencia. A continuación, utilice la plantilla cada vez que cree un nuevo documento. | Las plantillas proporcionan un punto de partida para crear nuevos documentos. Una plantilla puede incluir los estilos, formatos y diseños de página que se utilizan con frecuencia. Considere la posibilidad de crear una plantilla si a menudo utiliza el mismo diseño y estilo de página para los documentos. 


| Astra Control proporciona tres modos operativos que puedes asignar a tus usuarios para controlar cuidadosamente el acceso entre Astra Control y tu entorno de nube. | Astra Control te permite asignar uno de los tres modos operativos a los usuarios de tus cuentas de AWS. Los modos te permiten controlar cuidadosamente el acceso entre Astra Control y tu estado de nube en función de tus políticas DE TI. 
|===


== Utiliza muchas imágenes

La mayoría de las personas son estudiantes visuales. Utilice vídeos, diagramas y capturas de pantalla para mejorar el aprendizaje, dividir bloques de texto y proporcionar una indicación visual a los usuarios sobre dónde se encuentran en las instrucciones de tarea.

* Incluya una frase de introducción que describa la siguiente imagen: “La siguiente ilustración muestra los LED de la fuente de alimentación de CA en el panel posterior”.
* Consulte la ubicación de la ilustración como “siguiente” o “anterior”, no “arriba” o “abajo”.
* Utilice texto alternativo en elementos visuales incrustados.
* Si la imagen pertenece a un paso, incluya la imagen justo después del paso y la sangría para alinearla con el número de paso.


Mejores prácticas en capturas de pantalla:

* Incluya no más de 5 capturas de pantalla por tarea.
* No incluya texto en una captura de pantalla. Utilice en su lugar anotaciones numeradas.
* Sé prudente con las capturas de pantalla que elijas incluir. Las capturas de pantalla pueden desaparecer rápidamente.


Prácticas recomendadas en vídeos o animaciones:

* Los videos deben tener menos de 5 minutos de duración.


.Ejemplos
* https://docs.netapp.com/us-en/occm/concept_accounts_aws.html["Ejemplo #1 Obtenga información sobre las credenciales y los permisos de AWS"^]
* https://docs.netapp.com/us-en/bluexp-backup-recovery/concept-ontap-backup-to-cloud.html["Ejemplo #2 Protege tus datos de volúmenes de ONTAP con backup y recuperación de datos de BlueXP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/use/drplan-create.html["Ejemplo #3 Crear un plan de replicación (muestra capturas de pantalla en una tarea)"^]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-gcp-accounts.html#associate-a-marketplace-subscription-with-google-cloud-credentials["Ejemplo #4 Gestionar credenciales en el vídeo de BlueXP"^]




== Crear contenido que pueda ser canificable

Ayude a los lectores a encontrar contenido rápidamente organizando el texto bajo los encabezados de las secciones y usando listas y tablas. Los encabezados, oraciones y párrafos deben ser cortos y fáciles de leer. La información más importante debe ser proporcionada primero.

.Ejemplos
* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-modes.html["Ejemplo #1"^]
* https://docs.netapp.com/us-en/ontap-systems/asa-c800/install-detailed-guide.html["Ejemplo #2"^]




== Crear flujos de trabajo que ayuden a los usuarios a lograr su objetivo

Los usuarios leen nuestro contenido para lograr un objetivo específico. Los usuarios quieren encontrar el contenido que necesitan, lograr sus metas y ir a casa a sus familias. Nuestro trabajo no es documentar productos o características. Nuestro trabajo es documentar los objetivos de los usuarios. Los flujos de trabajo son la forma más directa de ayudar a los usuarios a lograr sus objetivos.

Un flujo de trabajo es una serie de pasos o subtareas que describen cómo alcanzar un objetivo de usuario. El alcance de un flujo de trabajo es un objetivo completo.

Por ejemplo, los pasos para crear un volumen no serían un flujo de trabajo, ya que crear un volumen en sí mismo no es un objetivo completo. Los pasos para poner el almacenamiento a disposición de un servidor ESX pueden ser un flujo de trabajo. Los pasos incluirán no solo la creación de un volumen, sino la exportación del volumen, la configuración de los permisos necesarios, la creación de una interfaz de red, etc.

Los flujos de trabajo se derivan de los casos prácticos de los clientes. Un flujo de trabajo muestra sólo la mejor manera de alcanzar el objetivo.



== Organice el contenido en función del objetivo del usuario

Ayude a los usuarios a encontrar información rápidamente organizando el contenido en función del objetivo que el usuario está tratando de lograr. Este estándar se aplica a la tabla de contenidos (navegación) de un sitio de documentación, así como a las páginas individuales que aparecen en el sitio.

Organice el contenido de la siguiente manera:

Primera entrada en la navegación izquierda (nivel alto):: Organice el contenido en torno a los objetivos que el usuario está tratando de lograr. Por ejemplo, la primera entrada en la navegación para el sitio podría ser «empezar» o «proteger datos».
Las entradas de segundo nivel en la navegación del sitio de documentación (nivel medio):: Organice el contenido alrededor de las amplias tareas que componen las metas.
+
--
Por ejemplo, la sección «Comenzar» podría incluir las siguientes páginas:

* Preparación de la instalación
* Instalar y configurar <product name>
* Configurar la licencia
* Lo que puede hacer a continuación


--
Páginas individuales (nivel detallado):: En cada página, organice el contenido en torno a las tareas individuales que componen las tareas amplias. Por ejemplo, el contenido que los usuarios necesitan para preparar para la instalación o configurar la recuperación ante desastres.
+
--
Una página puede describir una sola tarea o varias tareas. Si hay varias tareas, deben describirse en secciones separadas de la página. Cada sección debe centrarse en un solo aspecto de aprendizaje o hacer de la tarea amplia. Esto podría incluir alguna información conceptual y basada en referencias necesaria para completar la tarea.

--




== Escribir para un público global

Nuestra documentación es leída por muchos usuarios cuyo idioma principal no es el inglés. traducimos nuestro contenido a otros idiomas utilizando herramientas de traducción automática neuronal o traducción humana. Para apoyar a nuestra audiencia global, escribimos contenido que es fácil de leer y fácil de traducir.

Siga estas directrices para escribir para una audiencia global:

* Escribir frases cortas y sencillas.
* Utilice gramática y puntuación estándar.
* Utilice una palabra para un significado y un significado para una palabra.
* Utilice contracciones comunes.
* Utilice gráficos para aclarar o reemplazar texto.
* Evite incrustar texto en gráficos.
* Evite tener tres o más nombres en una cadena.
* Evitar antecedentes poco claros.
* Evitar la jerga, los coloquialismos y las metáforas.
* Evite ejemplos no técnicos.
* Evite utilizar retornos duros y espaciado.
* No uses humor ni ironía.
* No uses contenido discriminatorio.
* No uses un lenguaje sesgado por el género a menos que estés escribiendo para una persona específica.




== Directrices de la a a la Z.



=== acrónimos y abreviaturas

Utilice acrónimos y abreviaturas bien conocidos para la familiaridad, pero evite las oscuras que podrían afectar negativamente la claridad y la findabilidad. Para convenciones adicionales para acrónimos y abreviaturas, consulte la https://learn.microsoft.com/en-us/style-guide/welcome/["Guía de estilo de escritura de Microsoft"^].



=== voz activa (frente a voz pasiva)

Consulte <<Escribir activamente>>.



=== admoniciones

Las amonestaciones son una herramienta poderosa cuando se usan correctamente. Pueden llamar la atención sobre información importante, proporcionar consejos útiles o advertir a los usuarios sobre peligros potenciales. Cuando se usan en exceso, pierden su impacto y pueden llevar a la fatiga del usuario. Aquí hay algunas pautas para asegurar el uso efectivo de las amonestaciones.

Utilice las siguientes etiquetas para separar las admoniciones del flujo de contenido principal:

* NOTA Utilice LA NOTA para resaltar información importante que debe sobresalir del resto del texto. Sin embargo, evita usar NOTE para obtener información que no sea esencial para que los usuarios entiendan o completen una tarea. El propósito de una NOTA es llamar la atención del lector sobre puntos críticos que de otra manera podrían pasar por alto.
* Los consejos deben usarse con moderación, si es que lo hacemos, ya que nuestra política consiste en documentar la información de las mejores prácticas por defecto. Si es necesario, utilice LA SUGERENCIA para resaltar la información de mejores prácticas que ayude a los usuarios a usar un producto o completar un paso o tarea de forma más fácil y eficiente. Un CONSEJO debe proporcionar consejos útiles o atajos que pueden mejorar la experiencia del usuario.
* PRECAUCIÓN Utilice PRECAUCIÓN para advertir a los usuarios sobre condiciones o acciones que pueden conducir a resultados no deseados, incluyendo lesiones personales o daños al equipo. Se debe TENER PRECAUCIÓN para llamar la atención sobre los riesgos potenciales que el usuario debe evitar para evitar daños o interrupciones.
* PRÁCTICA recomendada Utilice LAS MEJORES PRÁCTICAS para resaltar formas óptimas de completar tareas o usar un producto. No son meras sugerencias, sino estrategias que han sido validadas por expertos o estándares de la industria.
+
** *¿Qué hace una MEJOR PRÁCTICA?* Se trata de una estrategia práctica y específica para tareas que ofrece ventajas claras y está respaldada por fuentes fiables.
** *¿Cuándo puedo usarlos?* Puede utilizar LAS MEJORES PRÁCTICAS para todos los tipos de contenido y todas las audiencias. Como CONSEJOS, úsalos con moderación para mantener su significado.
** * ¿Cómo los formateo?* Presente LAS MEJORES PRÁCTICAS en un formato coherente y fácil de usar. Esto podría ser una lista de viñetas, una lista numerada o un párrafo, dependiendo del contexto.




.Directrices adicionales
* Utilice sólo admoniciones admitidas. No se admite ningún otro tipo de formato.
* Evite el uso excesivo de amonestaciones. El uso excesivo puede hacer que los usuarios se salten estas secciones importantes porque las consideran el «cajón basura» de nuestros documentos.
* Como regla general, limite el número de amonestaciones a un máximo de 3 por página.
* Proporcionar información clara y concisa dentro de la admonición. El mensaje debe ser breve y al punto, permitiendo a los usuarios entender rápidamente la importancia de la información proporcionada.
* Evite las admoniciones de AsciiDoc en una tabla. Si el contenido debe identificarse como una nota, sugerencia o precaución, utilice Nota:, Consejo:, o Precaución: como introducción en línea del texto.




=== después (frente a «una vez»)

* Use “After” para indicar una cronología: “Encienda el ordenador después de conectarlo”.
* Utilice «una vez» solo para significar «una vez».




=== también

* Utilice "también" para indicar "adicionalmente".
* No utilice «tampoco» para decir «alternativamente».




=== y/o.

Elija el término más preciso si hay uno. Si ninguno de los términos es más preciso que el otro, use “AND/OR”.



=== como

No use “as” para significar “porque”.



=== utilizando (en comparación con «uso» o «con»)

* Utilice “mediante el uso” cuando la entidad que está haciendo el uso sea el asunto: “Puede agregar nuevos componentes al repositorio mediante el menú Componentes”.
* Puede iniciar una frase con «uso» o «con», que a veces son aceptables con nombres de producto: «Con SnapDrive, puede gestionar discos virtuales y copias snapshot en un entorno Windows».




=== can (frente a «podría», «puede», «debería» o «debe»)

* Utilice “CAN” para indicar la capacidad: “Puede confirmar los cambios en cualquier momento durante este procedimiento”.
* Utilice “podría” para indicar la posibilidad: “La descarga de varios programas puede afectar el tiempo de procesamiento”.
* No uses “puede”, lo cual es ambiguo porque podría significar capacidad o permiso.
* Utilice «should» para indicar una acción recomendada pero opcional. Considere usar una frase alternativa en su lugar, como “Recomendamos”.
* Evita usar “must” porque lo es <<Escribir activamente,pasivo>>. Considere la posibilidad de reestablecer el pensamiento como una instrucción utilizando la voz imperativa. Si utiliza “Must”, utilícelo para indicar una acción o condición requerida.




=== capitalización

Utilice mayúsculas de estilo de frase (minúsculas) para casi todo. Solo capitalice:

* La primera palabra de frases y encabezados, incluidos los títulos de las tablas
* La primera palabra de los elementos de la lista, incluidos los fragmentos de frase
* Unas adecuadas
* Títulos de documentos y subtítulos (capitalice todas las palabras y preposiciones principales de cinco o más letras)
* Elementos de la interfaz de usuario, pero solo si están capitalizados en la interfaz. De lo contrario, utilice minúsculas.




=== avisos de precaución

Consulte <<admoniciones>>.



=== contracciones

Uso <<contracciones,contracciones>> como parte de la escritura conversacional.



=== garantizar (frente a «confirmar» o «verificar»)

* Use «Asegurar» para decir «asegurarse». Incluya “Eso”, según corresponda: “Asegúrese de que haya suficiente espacio en blanco alrededor de las ilustraciones”.
* Nunca utilice «garantizar» para implicar una promesa o garantía: «Utilice Cloud Manager para asegurarse de que puede aprovisionar volúmenes NFS y CIFS en clústeres de ONTAP».
* Utilice «Confirmar» o «verificar» cuando haga referencia a que el usuario debe hacer doble clic en algo que ya existe o que ya ha sucedido: «Verifique que NFS está configurado en el clúster».




=== gráficos

Consulte <<Utiliza muchas imágenes>>.



=== gramática

Salvo que se indique lo contrario, siga las convenciones de gramática, puntuación y ortografía detalladas en:

* https://docs.microsoft.com/en-us/style-guide/welcome/["Guía de estilo de escritura de Microsoft"^]
* https://www.merriam-webster.com/["Merriam-Webster Diccionario en línea"^]




=== si no es así

No use “si no” por sí solo para referirse a la frase anterior:

* **En lugar de esto**: “La computadora debe estar apagada. De lo contrario, apáguelo.
* **Haga esto**: "Verifique que el ordenador esté apagado".




=== si (frente a «si» o «cuándo»)

* Use “if” para indicar una condición, como en “if this, then that” construcciones.
* Use “si” cuando haya una condición declarada o implícita “o no”. Para facilitar la traducción, a menudo es mejor reemplazar "ya sea o no" por "solo".
* Use “Cuándo” para indicar un paso del tiempo.




=== voz imperativa

Consulte <<Escribir activamente>>.



=== futuras funcionalidades o versiones

No te refieras al momento o contenido de las próximas versiones o funciones de productos, aparte de decir que una función o función no es compatible actualmente.



=== Artículos de KB: Referencia a.

Consulte los artículos de la base de conocimientos de NetApp (NetApp Knowledgebase) cuando corresponda. Para páginas de recursos y contenido de GitHub, coloque el vínculo en texto en ejecución.



=== listas

Las listas de información suelen ser más fáciles de escanear y absorber que los bloques de texto. Considere formas de simplificar la información compleja presentándola en forma de lista. A continuación se indican algunas directrices generales, pero use su criterio:

* Asegúrese de que el motivo de la lista está claro. Introduzca la lista con una frase completa, un fragmento de frase con dos puntos o un encabezado.
* Cuando utilice una lista dentro de una lista, limite la estructura a dos niveles como máximo de profundidad para mantener la claridad y la legibilidad. Si te encuentras con que necesitas más niveles, considera reorganizar el contenido para que sea más fácil para los usuarios navegar y entender.
* Cualquier lista, incluidas las listas anidadas, debe tener entre dos y siete entradas. En general, cuanto más corta sea la información de cada entrada, más entradas podrá agregar mientras mantiene la lista en un estado de exploración. Si una lista tiene varias entradas que contienen listas anidadas, considere el uso de secciones o títulos de bloque para dividir todo el elemento en fragmentos más consumibles.
* Las entradas de lista deben ser lo más explorables posible. Evite bloques de texto que se puedan escanear para mantener las entradas de la lista.
* Las entradas de la lista deben comenzar con una letra mayúscula, y las entradas de la lista deben ser gramaticalmente paralelas. Por ejemplo, comience cada entrada con un sustantivo o un verbo:
+
** Si todas las entradas de la lista son frases completas, terminarlas con períodos.
** Si todas las entradas de la lista son fragmentos de frases, no las termine con puntos.


* Las entradas de lista deben ordenarse de forma lógica, como alfabéticamente o cronológicamente.




=== localización

Consulte <<Escribir para un público global>>.



=== minimalismo

Consulte <<Escribir como mínimo>>.



=== números

* Utilice números arábigos para 10 y todos los números mayores de 10, con las siguientes excepciones:
+
** Si comienza una frase con un número, utilice una palabra, no un número árabe.
** Utilice palabras (no números) para números aproximados.


* Utilice palabras para números menores de 10.
* Si una frase contiene una mezcla de números menores de 10 y mayores de 10, utilice números árabes para todos los números.
* Para obtener más convenciones numéricas, consulte https://docs.microsoft.com/en-us/style-guide/welcome/["Guía de estilo de escritura de Microsoft"^].




=== plagio

Documentamos los productos de NetApp y la interacción de los productos de NetApp con productos de terceros. No documentamos productos de terceros. Nunca deberíamos copiar y pegar contenido de terceros en nuestros documentos y no deberíamos hacerlo nunca.



=== requisitos previos

Los requisitos previos identifican las condiciones que deben existir o las acciones que los usuarios deben haber completado antes de iniciar la tarea actual.

* Identifique la naturaleza del contenido con un encabezado, como «Requisitos previos», «Antes de empezar» o «Antes de empezar».
* Utilice la voz pasiva para la redacción de los requisitos previos si tiene sentido hacerlo:
+
** «Debe configurarse NFS o CIFS en el clúster».
** «Debe tener la dirección IP de gestión de clúster y la contraseña de la cuenta de usuario administrador para añadir el clúster a Cloud Manager».


* Clarifique el requisito previo según sea necesario: «NFS o CIFS debe configurarse en el clúster. Puede configurar NFS y CIFS mediante System Manager o la CLI».
* Considere otras formas de presentar la información, por ejemplo, si sería apropiado volver a escribir el contenido como el primer paso de la tarea actual:
+
** Requisito previo: «Debe tener los permisos necesarios antes de poner en marcha el primer clúster».
** Paso: «Proporcione los permisos necesarios para poner en marcha su primer clúster».






=== anterior (frente a «anterior», «anterior» o «anterior»)

* Si es posible, sustituya el anterior por el anterior.
* Si no puedes usar “Antes”, usa “Prior” como adjetivo para referirse a algo que ocurrió antes en el tiempo o con un orden de importancia superior.
* Utilice 'Previous' para indicar algo que ocurrió antes en un momento no especificado.
* Utilice la opción Anterior para indicar algo que ha ocurrido inmediatamente con anterioridad.




=== signos de puntuación

Simplifique. En general, mientras más puntuación se incluya en una frase, más células cerebrales se necesita entender.

* Use una coma serie (coma Oxford) antes de la conjunción (“y” o “o”) en una lista narrativa de tres o más elementos.
* Limite el uso de punto y coma.
* Salvo que se indique lo contrario, siga las convenciones de gramática, puntuación y ortografía detalladas en:
+
** https://docs.microsoft.com/en-us/style-guide/welcome/["Guía de estilo de escritura de Microsoft"^]
** https://www.merriam-webster.com/["Merriam-Webster Diccionario en línea"^]






=== desde entonces

Use “since” para indicar un paso del tiempo. No use “since” para significar “porque”.



=== ortografía

Salvo que se indique lo contrario, siga las convenciones de gramática, puntuación y ortografía detalladas en:

* https://docs.microsoft.com/en-us/style-guide/welcome/["Guía de estilo de escritura de Microsoft"^]
* https://www.merriam-webster.com/["Merriam-Webster Diccionario en línea"^]




=== eso (frente a «qué» o «quién»)

* Use “Eso” (sin una coma final) para introducir cláusulas que sean necesarias para que la frase tenga sentido.
* Usa “Eso” incluso si la frase es clara en inglés sin ella: “Compruebe que el ordenador está apagado”.
* Utilice “which” (con una coma final) para introducir cláusulas que añadan información complementaria pero que no sean necesarias para que la frase tenga sentido.
* Utilice “Who” para introducir cláusulas que hagan referencia a personas.




=== marcas comerciales

No incluimos símbolos de marca en la mayoría de nuestro contenido técnico porque las declaraciones legales en nuestras plantillas son suficientes. Sin embargo, sí seguimos todas las reglas de uso cuando las utilizamos https://www.netapp.com/us/legal/netapptmlist.aspx["Condiciones de Marca comercial de NetApp"^]:

* Use términos de marcas (con o sin el símbolo) sólo como adjetivos, nunca como sustantivos, verbos o verzales.
* No abrevie, hifenato ni cursiva términos marcas registradas.
* No pluralice los términos con marcas registradas. Si se requiere una forma plural, use el nombre de la Marca registrada como adjetivo que modifica un sustantivo plural.
* No uses una forma posesiva de un término de marca registrada. Puede utilizar la forma posesiva de nombres de empresa, como NetApp, cuando los nombres se utilizan en sentido general, en lugar de como términos de Marca comercial.




=== interfaz de usuario

Cuando esté documentando una interfaz de usuario, confíe en la interfaz tanto como sea posible para guiar al usuario.

.Directrices generales
Utilice un estilo simple y mímico al documentar las interfaces de usuario.

[%collapsible]
====
* Supongamos que el usuario está utilizando la interfaz mientras lee el contenido:
+
** No guíe al usuario a través de un asistente o pantalla paso a paso. Sólo llame a las cosas importantes que no son aparentes desde la interfaz.
** No incluya «clic en Aceptar», «clic en Guardar» o «se ha creado el volumen» o cualquier otra cosa que resulte obvio para alguien que esté realizando la tarea.
** Presuponga éxito. A menos que espere que una operación falle la mayoría de las veces, no documente la ruta de fallos. Supongamos que la interfaz proporciona una guía adecuada.


* No utilice el clic. Siempre use “seleccionar” porque esa palabra cubre el ratón, el tacto, el teclado y cualquier otra forma de hacer una elección.
* Centre el contenido en un flujo de trabajo que aborde un caso de uso del cliente y haga que el usuario tenga el lugar adecuado en la interfaz para iniciar el flujo de trabajo.
* Documente siempre la mejor manera de lograr el objetivo del usuario.
* Si el flujo de trabajo requiere una decisión significativa, asegúrese de documentar una regla de decisión.
* Utilice el número mínimo de pasos necesario para la mayoría de usuarios la mayor parte del tiempo.


====
.Nomenclatura de los elementos de la IU
Evite documentar el nivel de granularidad que requiera la nomenclatura de elementos de la interfaz de usuario.

[%collapsible]
====
Confíe en la interfaz para guiar al usuario a través de los detalles de la interacción. Si debe obtener ese valor específico, asigne un nombre a la etiqueta en el elemento. Por ejemplo, “Seleccione el volumen deseado” o “Seleccione “Usar volumen existente”. No hay necesidad de nombrar menús, botones de radio o casillas de verificación, solo use la etiqueta.

Para los iconos que deben seleccionar los usuarios, utilice una imagen del icono. No intente nombrarlo. Esta regla se aplica a iconos como la flecha, lápiz, engranaje, kabob, hamburguesa, y así sucesivamente.

====
.Representación de las etiquetas mostradas
Siga la ortografía y el uso de mayúsculas que utiliza la interfaz de usuario al identificar etiquetas.

[%collapsible]
====
Si a una etiqueta le siguen tres puntos, no incluya los tres puntos al asignar nombre al objeto. ANIME a los desarrolladores a utilizar mayúsculas en el estilo de título para las etiquetas de interfaz de usuario, para que la escritura sea más sencilla.

====
.Uso de capturas de pantalla
Utilice las capturas de pantalla con moderación.

[%collapsible]
====
Una captura de pantalla ocasional (captura de pantalla) ayuda a los usuarios a estar seguros de que están en el lugar correcto en una interfaz al iniciar o cambiar interfaces durante un flujo de trabajo. No utilice capturas de pantalla para mostrar qué datos introducir o qué valor seleccionar.

====


=== mientras (frente a «aunque»)

* Utilice «Mientras» para indicar algo que ocurre en el tiempo.
* Utilice “Aunque” para representar una actividad que ocurre casi al mismo tiempo o poco después de otra actividad.

